/**
 * App ID for the skill
 */
const APP_ID = undefined; //replace with "amzn1.echo-sdk-ams.app.[your-unique-value-here]";

/**
 * The AlexaSkill prototype and helper functions
 */
const AlexaSkill = require('./AlexaSkill');

const wordsmithAPIKey = '3861c2becc354261579e06cae7bbbc775dc1c08db5b039c4a514831375823189';
const wordsmith = require('wordsmith-node-sdk')(wordsmithAPIKey, 'GreatCall'); // Make a unique user agent for your app

/**
 * MyAlexaSkill is a child of AlexaSkill.
 * To read more about inheritance in JavaScript, see the link below.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript#Inheritance
 */
const MyAlexaSkill = function () {
    AlexaSkill.call(this, APP_ID);
};

// Extend AlexaSkill
MyAlexaSkill.prototype = Object.create(AlexaSkill.prototype);
MyAlexaSkill.prototype.constructor = MyAlexaSkill;

MyAlexaSkill.prototype.eventHandlers.onSessionStarted = function (sessionStartedRequest, session) {
    console.log("MyAlexaSkill onSessionStarted requestId: " + sessionStartedRequest.requestId
        + ", sessionId: " + session.sessionId);
    // any initialization logic goes here
};

MyAlexaSkill.prototype.eventHandlers.onLaunch = function (launchRequest, session, response) {
    console.log("MyAlexaSkill onLaunch requestId: " + launchRequest.requestId + ", sessionId: " + session.sessionId);
    const speechOutput = "YOUR WELCOME MESSAGE";
    const repromptText = "YOUR REPROMPT FOR USER INPUT";
    response.ask(speechOutput, repromptText);
};

MyAlexaSkill.prototype.eventHandlers.onSessionEnded = function (sessionEndedRequest, session) {
    console.log("MyAlexaSkill onSessionEnded requestId: " + sessionEndedRequest.requestId
        + ", sessionId: " + session.sessionId);
    // any cleanup logic goes here
};

MyAlexaSkill.prototype.intentHandlers = {
    // register custom intent handlers
    "GetCurrentStatusIntent": function (intent, session, response) {
      wordsmith.projects.find('lively-narrative')
        .then(project => project.templates.find('lively-narrative-v1'))
        .then(template => template.generate(
                {
                  "userid": 1,
                  "name": "Shelley High",
                  "alias": "Mom",
                  "gender": "Female",
                  "relationship": "Mom",
                  "steps": 4534,
                  "challengescompleted": 2,
                  "pointsearned": 8546,
                  "lastknownlocation": "Home",
                  "lastknownlocationtimestamp": 12
                }
          ))
        .then((content) => {
          // content is the text generated by Wordsmith
          response.tell(content, content);
        })
        .catch((error) => {
          console.error(error);
        });
    }
};

// Create the handler that responds to the Alexa Request.
exports.handler = function (event, context) {
    // Create an instance of the MyAlexaSkill skill.
    const myAlexaSkill = new MyAlexaSkill();
    myAlexaSkill.execute(event, context);
};
